name: 🐛 Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: bug

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide as much information as possible.

  - type: input
    id: description
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is.

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Please provide clear steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error

  - type: input
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What you expected to happen

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, browser, Node/Python version, etc.
      placeholder: e.g. Windows 11, Chrome 109, Node v18

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      placeholder: Add any other context about the problem here.
