"""add_provider_and_external_id_to_accounts

Revision ID: 8b5891c8ab93
Revises: 
Create Date: 2026-01-12 19:12:14.625220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b5891c8ab93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('provider', sa.String(length=50), nullable=True))
    op.add_column('accounts', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('accounts', sa.Column('balance_available', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'balance_available')
    op.drop_column('accounts', 'external_id')
    op.drop_column('accounts', 'provider')
    # ### end Alembic commands ###
